name: Security Quality Gate
on:
  push:
    branches:
      - main
jobs:
  tfsec_scan:
    name: tfsec SAST Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run tfsec Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          additional_args: --soft-fail=true
